version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-hardcore_fashion}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "5433:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 ecommerce.asgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-False}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1}
      OTP_HASH_SECRET: ${OTP_HASH_SECRET}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:8000}

      DB_NAME: ${DB_NAME:-hardcore_fashion}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}



      # ----------------------------
      # Flutterwave
      # ----------------------------
      
      FLUTTERWAVE_PUBLIC_KEY: ${FLUTTERWAVE_PUBLIC_KEY}
      FLUTTERWAVE_SECRET_KEY: ${FLUTTERWAVE_SECRET_KEY}
      FLUTTERWAVE_ENV: ${FLUTTERWAVE_ENV:-test}


    depends_on:
      - db

volumes:
  postgres_data:
