# Generated by Django 4.2.7 on 2026-07-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_vendor_product_vendor_vendororder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='is_active',
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
