# Generated by Django 6.0.7 on 2026-07-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, default='', help_text='e.g. Home, Work', max_length=60),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='preferred_currency',
            field=models.CharField(default='RWF', max_length=8),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='balance_after',
            field=models.PositiveIntegerField(help_text='Running balance after this transaction'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='points',
            field=models.IntegerField(help_text='Positive = earned, negative = spent/adjusted'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('flutterwave', 'Flutterwave'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money'), ('stripe', 'Stripe'), ('cod', 'Cash on Delivery')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='1–5 stars'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='True when the message is sent by admin/staff'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payout_details',
            field=models.JSONField(blank=True, default=dict, help_text='Gateway-specific account details'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payout_method',
            field=models.CharField(blank=True, default='', help_text='flutterwave | paypal | mobile_money | bank_transfer', max_length=50),
        ),
    ]
