# Generated by Django 4.2.7 on 2026-07-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_address_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorVerification',
            fields=[],
            options={
                'verbose_name': 'Verify vendor',
                'verbose_name_plural': 'Verify vendors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.vendor',),
        ),
    ]
