# Generated by Django 6.0.7 on 2026-07-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_cart_session_key_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Estimated days to ship'),
        ),
    ]
